# Versión de la sintaxis de Docker Compose.
version: '3'

services:
  app:
    image: pryTopicos/reciclaje_usat # Define la imagen del contenedor para la aplicación.
    ports:
      - "8080:80" # Mapea el puerto 8080 del host al puerto 80 del contenedor.
    depends_on:
      - db # Especifica que este servicio depende del servicio de base de datos (db).
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: recicla_usat
      DB_USERNAME: root
      DB_PASSWORD:
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 60m php artisan migrate"

  db:
    image: mysql # Define la imagen del contenedor para la base de datos MySQL.
    environment:
      MYSQL_DATABASE: recicla_usat # Nombre de la base de datos que se creará al iniciar el contenedor.
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Permite una contraseña vacía para el usuario root de MySQL.
