version: '3'

services:
  app:
    build:
      context: . # Construye la imagen desde el Dockerfile en el directorio actual.
      dockerfile: Dockerfile
    image: proyecto-reciclaje # Nombre de la imagen local construida.
    ports:
      - "8080:80" # Mapea el puerto 8080 del host al puerto 80 del contenedor.
    depends_on:
      - db # Depende del servicio de base de datos.
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: proyectoGrupal
      DB_USERNAME: root
      DB_PASSWORD: ""
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 60m php artisan migrate"

  db:
    image: mysql:8.0 # Especifica la versión de MySQL.
    environment:
      MYSQL_DATABASE: proyectoGrupal
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306" # Expone el puerto de MySQL para conectarse desde el host.
