version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: josuecumpa/proyecto-reciclaje:latest
    ports:
      - "8081:80" # Mapea el puerto 80 del contenedor al 8081 del host
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:GENERATED_KEY_HERE
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: proyectoGrupal
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/var/www/html
    command: sh -c "while ! nc -z db 3306; do sleep 1; done && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=80"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectoGrupal
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    tmpfs: # Define un volumen temporal en memoria
      - /var/lib/mysql
    ports:
      - "3306:3306"